remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [DSCI 551 Final Project]
description: [Extracting Information From MRI Images to Predict Alzheimer's Disease Using Machine Learning
\n Yishan Li and Xinyue Yu]

